# https://www.gitpod.io/docs/configure/workspaces/workspace-image#workspace-image
image: 
  file: .gitpod.Dockerfile

# image: gitpod/workspace-mysql

# https://www.gitpod.io/docs/configure/authentication/github#github
github:
  prebuilds: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Initialization
    init: composer install
    command: wp db create && wp db import .db/db.sql && wp server --host=0.0.0.0 --port=8080
  - command: php -S 0.0.0.0:3333 -t .utils
  - command: .gitpod/info.sh

ports:
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 3333
    onOpen: ignore