# https://www.gitpod.io/docs/configure/workspaces/workspace-image#workspace-image
image: 
  file: .gitpod.Dockerfile

# image: gitpod/workspace-mysql

# https://www.gitpod.io/docs/configure/authentication/github#github
github:
  prebuilds: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: ports await 8080 && sh .gitpod/info.sh
  - name: Initialization
    init: sh .gitpod/config.sh && wp core download && composer install && sh .gitpod/dotenv.sh
    command: wp core downlaod && wp config create && wp config set DB_NAME wordpress && wp config set DB_USER root

ports:
  - port: 1-10000
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
