# https://www.gitpod.io/docs/configure/workspaces/workspace-image#workspace-image
image:
  file: .gitpod.Dockerfile

# https://www.gitpod.io/docs/configure/authentication/github#github
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    main: true
    branches: true
    addCheck: true
    addBadge: true
    addLabel: true
    addComment: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: wordpress
    before: composer create-project roots/bedrock tmp && md db
    init: |
      cat tmp/README.md >> README.md && mv -f README.md tmp/README.md
      cat tmp/.gitignore >> .gitignore && mv -f .gitignore tmp/.gitignore
      mv -f .distignore tmp/.distignore
      cp -f tmp/* . && rm -rf tmp
      wp server --host=0.0.0.0 --port=3000
    command: gp preview $(gp url 3000)

  - name: sqlite
    before: |
      mkdir db && cd db
      wget https://github.com/vrana/adminer/releases/download/v4.8.1/editor-4.8.1-en.php adminer.php
      chmod 640 adminer.php
      sqlite3 gitpod.sqlite3
      chmod 777 gitpod.sqlite3
    init: |
      gp ports await 3000
      cd db
      php -S 0.0.0.0:8080 -t db adminer.php
    command: gp preview $(gp url 8080)

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Web
    port: 3000
    onOpen: open-browser

  - name: Adminer
    port: 8080
    onOpen: open-browser