# https://www.gitpod.io/docs/configure/workspaces/workspace-image#workspace-image
image:
  file: .gitpod.Dockerfile

# https://www.gitpod.io/docs/configure/authentication/github#github
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    main: true
    branches: true
    addCheck: true
    addBadge: true
    addLabel: true
    addComment: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: wordpress
    before: |
      brew unlink php
      brew link php@8.0
      echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.0/bin:$PATH"' >> /home/gitpod/.bash_profile
      echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.0/sbin:$PATH"' >> /home/gitpod/.bash_profile
      composer create-project roots/bedrock tmp
      cat tmp/README.md >> README.md && mv -f README.md tmp/README.md
      cat tmp/.gitignore >> .gitignore && mv -f .gitignore tmp/.gitignore
      cp -f -r tmp/. . && rm -rf -r tmp
      touch web/phpinfo.php && echo '<?php phpinfo();' >> web/phpinfo.php
      chmod 640 web/phpinfo.php
      gp sync-done init
    init: |
      gp sync-await init
      wp server --host=0.0.0.0 --port=3000
    command: gp preview $(gp url 3000)

  - name: sqlite
    before: |
      gp sync-await init
      mkdir db && cd db
      wget https://github.com/vrana/adminer/releases/download/v4.8.1/editor-4.8.1-en.php -O adminer.php
      chmod 640 adminer.php
      touch gitpod.sqlite
    init: |
      gp ports await 3000
      gp sync-done sqlite
    command: gp sync-await sqlite && php -S 0.0.0.0:8080 adminer.php & gp preview $(gp url 8080)

  - name: info
    init: gp sync-done sqlite
    command: |
      echo "wp/web: $(gp url 3000)"
      echo "wp/admin: $(gp url 3000)/admin"
      echo "wp/user:"
      echo "username: root"
      echo "password: root"
      echo "--------------------------------------"
      echo "php/info: $(gp url 3000)/phpinfo.php"
      echo "db/adminer: $(gp url 8080)"
      echo "--------------------------------------"
      echo "gp/path:" $(readlink -f .)
      echo "gp/workspace info:"
      gp info
      echo "gp/git remotes"
      git remote -v

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Web
    port: 3000
    onOpen: open-browser

  - name: Adminer
    port: 8080
    onOpen: open-browser

  - port: 5000-8079
    onOpen: ignore