github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    branches: true
    addCheck: true
    addBadge: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: brew install sqlite3 wp-cli php@8.0 && brew unlink php && brew link php@8.0
    init: composer create-project --prefer-dist roots/bedrock .tmp \
            && rm --rf .git -f \
            && mv .tmp/* . \
            && composer require \
              wpackagist-plugin/acf-extended \
    command: wp server --host=0.0.0.0 --port=3000

  - init: |
      gp awaits -p 3000
      gp preview $(gp url 3000)
      cd .db
      wget https://github.com/vrana/adminer/releases/download/v4.8.1/editor-4.8.1-en.php -O index.php
      sqlite3 development.sqlite3
    command: cd .db chmod 777 development.sqlite3 && chmod 777 index.php && php -S 0.0.0.0:8080
  - init: gp port awaits 8080
    command: gp preview $(gp url 8080)

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Web App
    port: 3000
    onOpen: open-browser

  - name: Adminer
    port: 8080
    onOpen: open-browser