# https://www.gitpod.io/docs/configure/workspaces/workspace-image#workspace-image
image:
  file: .gitpod.Dockerfile

# https://www.gitpod.io/docs/configure/authentication/github#github
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    branches: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: wordpress
    before: |
      echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.0/bin:$PATH"' >> /home/gitpod/.bash_profile
      echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.0/sbin:$PATH"' >> /home/gitpod/.bash_profile
    init: |
      wp package install aaemnnosttv/wp-cli-dotenv-command:^2.0
      composer create-project roots/bedrock tmp
      cat tmp/README.md >> README.md && mv -f README.md tmp/README.md
      cat tmp/.gitignore >> .gitignore && mv -f .gitignore tmp/.gitignore
      cp -f -r tmp/. . && rm -rf -r tmp
      touch web/phpinfo.php && echo '<?php phpinfo();' >> web/phpinfo.php
      chmod 640 web/phpinfo.php
      wget https://raw.githubusercontent.com/aaemnnosttv/wp-sqlite-db/master/src/db.php -O web/app/db.php
      chmod 640 web/phpinfo.php
      composer require andriilive/wp-disable-generated-image-sizes andriilive/wp-cli-media-regenerate-svg-fix lukasbesch/bedrock-plugin-disabler roots/soil lukasbesch/bedrock-plugin-disabler
      wp core install --url=$(gp url 3000) --title="Wordpress by DigitalAndy.eu" --admin_user="root" --admin_password="root" --admin_email="example@example.com" --skip-email
      wp dotenv salts regenerate
      wp dotenv set DB_NAME wordpress
      wp dotenv set DB_USER root
      wp dotenv set DB_PASSWORD root
      wp dotenv set WP_HOME $(gp url 3000)
      gp sync-done init
    command: gp sync-await sqlite && gp sync-await init && wp server --host=0.0.0.0 --port=3000 & gp preview $(gp url 3000)

  - name: sqlite
    before: |
      gp sync-await init
      mkdir db
      wget https://github.com/vrana/adminer/releases/download/v4.8.1/editor-4.8.1-en.php -O db/adminer.php
      chmod 640 db/adminer.php
    init: |
      gp ports await 3000
      php -S 0.0.0.0:8080 db/adminer.php
    command: sqlite3 web/app/database/.ht.sqlite && gp sync-done sqlite

  - name: info
    init: gp ports await 8080
    command: |
      echo "wp/web: $(gp url 3000)"
      echo "wp/admin: $(gp url 3000)/wp/wp-login.php"
      echo "wp/user:"
      echo "username: root"
      echo "password: root"
      echo "wp/env:"
      wp dotenv list
      echo "--------------------------------------"
      echo "php/info: $(gp url 3000)/phpinfo.php"
      echo "db/adminer: $(gp url 8080)"
      echo "db/info:"
      # echo sqlite3 web/app/database/.ht.sqlite -e '.dbinfo'
      echo "--------------------------------------"
      echo "gp/path:" $(readlink -f .)
      echo "gp/workspace info:"
      gp info
      echo "gp/git remotes"
      git remote -v

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Web
    port: 3000
    onOpen: open-browser

  - name: Adminer
    port: 8080
    onOpen: notify

  - port: 5000-8079
    onOpen: ignore

vscode:
  extensions:
    - alexcvzz.vscode-sqlite
    - bmewburn.vscode-intelephense-client
    - johnbillion.vscode-wordpress-hooks