# https://www.gitpod.io/docs/configure/workspaces/workspace-image#workspace-image
image: 
  file: .gitpod.Dockerfile

# image: gitpod/workspace-mysql

# https://www.gitpod.io/docs/configure/authentication/github#github
github:
  prebuilds: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: ports await 8080 && sh .gitpod/info.sh
  - name: Initialization
    init: sh .gitpod/config.sh && \
          wp config create --dbname=wordpress --dbuser=root --dbhost=0.0.0.0 --homeurl=$(gp url 8080) && \
          wp core downlaod && composer install
    command: wp core install --url=$(gp url 8080) --title="Wordpress on GitPod" --admin_user="root" --admin_password="root" --admin_email="example@example.com" --skip-email && \
             sh .gitpod/sca.sh && cd wp-content/themes && composer create-project roots/sage theme && cd theme && \
             pnpm && pnpm dev

ports:
  - port: 1-10000
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
